name: Deployment Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --no-found --no-optional
      - name: Lint code
        run: npm run lint